FROM  ghcr.io/rocker-org/devcontainer/tidyverse:4.5

# Adding R packages
RUN install2.r --error cpp11 roxygen2 tinytest data.table netplot \
  devtools decor DiagrammeR

RUN install2.r --error languageserver && \
  installGithub.r nx10/httpgd

RUN apt-get update && apt-get install --no-install-recommends -y nano

RUN installGithub.r UofUEpiBio/measles@main

CMD ["bash"]
